More data from the place
JustAnotherArchivist/snscrape pull request #218
Opened 2021-04-19 17:08 UTC by NoeCampos22

While building dash maps, attributes like the country name/code could be useful. So, I added that aside from the place name the tweets scrapper also includes the country name, country code and the place name.

2021-04-19 19:16 UTC, JustAnotherArchivist requested changes
Thank you! Yes, extracting this sounds useful.

Since these fields are all closely related, I think it makes sense to instead change `Tweet.place` to a `Place` dataclass with the relevant attributes `fullName`, `name`, `type`, `country`, and `countryCode`. #209 isn't part of any release yet, so changing the structure isn't an issue, and it keeps the `Tweet` object cleaner.
(Note the capitalisation convention I use in my code. The `Place` class should go below `Coordinates`.)

2021-04-19 19:16 UTC, JustAnotherArchivist commented on snscrape/modules/twitter.py
> +			# get place data
```suggestion
```

This is obvious from the code.

2021-04-20 01:45 UTC, JustAnotherArchivist approved these changes
Looks good, thank you!

2021-04-20 01:45 UTC, merged

2021-04-20 05:12 UTC, NoeCampos22 commented
Glad to help! Thank you!